### PR TITLE
added random_fo for random fuck offs :)

### PR DESCRIPTION
**Pull request by JackStat**
Some of the whitespace removals were done by my code editor automatically.  I can remove those changes if they bother you.  I just wanted to be able to call a random function so I could be more surprised by what came out :)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Some of the whitespace is my fault. I don't always tell Emacs (ie not on all my machines, it seems) to remove trailing whitespave.

Patch is fine _per se_ if one wanted to deviate from FOAAS which is hadn't yet.  As I recall, they had planned to over something random at some point...

But I like how you overcame the name & from constraint. Nice.  I guess I would have to maintain that going forward.

Now, and here is the clincher:  can we get this a little closer to my usual R coding style and get rid of the underscores?  :-/    As for `random_fo`, maybe `randomFO` or even just `random` ?

**Comment by JackStat** [comment]
No problem sir. I definitely want to fit your coding style so if there is anything else I need to change just say the word.  I left the action words on their own lines so we could comment them out easily if FOAAS zapped any of them in the future as it seems they have done before.  Great package!

**Comment by eddelbuettel** [comment]
Well you left the manual page behind, and you didn't de-underscore (not that it matters That F^%$ing Much ;-) ) the variables.

But I appreciate it -- let's chat here real briefly so that we don't need another iteration.  Regarding `random()`:
- in favour: nice and sweet verb, no camelcase or snakecase to upset either camp :)
- against: too common, clash with other functions names likely

So I think I am leaning toward something like `randomFO()` or maybe even `getRandomFO()` which makes it a little clearer we added an accessor.   

Thoughts?

**Comment by JackStat** [comment]
F^%$! I missed the docs... I had the same concerns about `random`.  I think I am leaning toward `getRandomFO()`

**Comment by eddelbuettel** [comment]
Me too. Want to give that a pass, then please do run `R CMD build ...; R CMD check --as-cran ...` on it and if clean push a commit.  Happy to fold that in.

**Comment by JackStat** [comment]
Version change?  already at 0.1.9

**Comment by eddelbuettel** [comment]
I have a mental TODO to catch up with FOAAS which got 1.0 recently.  There are a number of new access points ...

But one thing at a time.

**Pull request merged**
